DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Peli CASCADE;
DROP TABLE IF EXISTS KaPe CASCADE;
DROP TABLE IF EXISTS Maa CASCADE;
DROP TABLE IF EXISTS Maaruutu CASCADE;
DROP TABLE IF EXISTS Vesiruutu CASCADE;
