DROP TABLE IF EXISTS Player CASCADE;
DROP TABLE IF EXISTS Game CASCADE;
DROP TABLE IF EXISTS PlaGa CASCADE;
DROP TABLE IF EXISTS Country CASCADE;
DROP TABLE IF EXISTS Land CASCADE;
DROP TABLE IF EXISTS Water CASCADE;
